name: flutter_bilimdler
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  flame: ^1.15.0
  shared_preferences: ^2.2.2
  particles_flutter: ^0.1.4
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10
  xml: ^6.5.0
  path_drawing: ^1.0.1
  confetti: ^0.7.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - lib/Images/     # если используешь эту папку для логотипа
