// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvvu2QuO3yvJtRtC63Yc25goluu9sdNO0',
    appId: '1:200422882200:web:ac7a104bd263cc588689ed',
    messagingSenderId: '200422882200',
    projectId: 'bilimapp-f3fe2',
    authDomain: 'bilimapp-f3fe2.firebaseapp.com',
    storageBucket: 'bilimapp-f3fe2.firebasestorage.app',
    measurementId: 'G-QHP3PGDZEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8FJVop3xRJzh7pMw4FUbgqCur_5io-Mw',
    appId: '1:200422882200:android:e1725735b027add08689ed',
    messagingSenderId: '200422882200',
    projectId: 'bilimapp-f3fe2',
    storageBucket: 'bilimapp-f3fe2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAv15R8PVcFH57NZMU0cH7fDmI73EMJJQ',
    appId: '1:200422882200:ios:41acd3d0d75234568689ed',
    messagingSenderId: '200422882200',
    projectId: 'bilimapp-f3fe2',
    storageBucket: 'bilimapp-f3fe2.firebasestorage.app',
    iosBundleId: 'com.example.flutterBilimdler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAv15R8PVcFH57NZMU0cH7fDmI73EMJJQ',
    appId: '1:200422882200:ios:41acd3d0d75234568689ed',
    messagingSenderId: '200422882200',
    projectId: 'bilimapp-f3fe2',
    storageBucket: 'bilimapp-f3fe2.firebasestorage.app',
    iosBundleId: 'com.example.flutterBilimdler',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvvu2QuO3yvJtRtC63Yc25goluu9sdNO0',
    appId: '1:200422882200:web:28fcfb6c1999309f8689ed',
    messagingSenderId: '200422882200',
    projectId: 'bilimapp-f3fe2',
    authDomain: 'bilimapp-f3fe2.firebaseapp.com',
    storageBucket: 'bilimapp-f3fe2.firebasestorage.app',
    measurementId: 'G-MZGKETG3DH',
  );
}
